### ISSUE TITLE
Wine version

### ISSUE THREAD

**Issue by Manouchehri** [intezer/docker-ida#11]
@williballenthin has already written a short Dockerfile for running IDA in Wine, so it shouldn't be too difficult to get docker-ida working with the Windows release (instead of the native Linux version).

https://gist.github.com/williballenthin/1c6ae0fbeabae075f1a4

[Xvfb should replace X11 forwarding](https://superuser.com/a/948200) so Wine can run headless.

I will probably end up doing this myself in the upcoming weeks. (I'll send a PR if/when it's done.)

**Comment by ItaiTevet** [comment]
Hey Manouchehri,
Thank for you contribution, we would love to see your work once it's done.

**Comment by Manouchehri** [comment]
Released it back during DEFCON, forgot to mention it here too. Didn't get as much interest as I expected.. =( 

https://github.com/thawsystems/docker-ida
